---
title: "Opioid death rate prediction of California"
author: "Jiayi Liu"
date: ' May 15, 2018'
output:
  html_document:
    df_print: paged
  html_notebook: default
  word_document: default
  pdf_document: default
---



## Install packages
 
```{r}
library(MASS)
library(car)
library(psych)
library(carData)
library(corrplot)
```
 
## Load data and summary data
 
```{r}
opioid = read.table("LRdata.csv", sep=',', header = TRUE)
str(opioid)
summary(opioid)
```
 
## Data visualization
 
```{r}
# histogram of factors

par(mfrow=c(3,2))
hist(opioid$Unemployment)
hist(opioid$Poverty)
hist(opioid$Median.Income)
hist(opioid$Home.Price)
hist(opioid$no.high.school)

```
 

 
```{r}
#look at correlations, scatterplots
scatterplotMatrix(~Death.Rate+Unemployment+Poverty+Median.Income+Home.Price+no.high.school,data=opioid, smooth = FALSE, ellipse="FALSE", main="Simple Scatterplot Matrix")
# cor(opioid[,2:7])
# corr.test(opioid[,2:7], y = NULL, use ="pairwise",method="pearson",adjust="holm",alpha=.05)
```

```{r}
##more on correlation plots with p-values

M <- cor(opioid[,2:7])
corrplot(M,method="number")
corrplot(M,method="pie")
corrplot.mixed(M)

# matrix of the p-value of the correlation
p.mat <- cor.mtest(opioid[,2:7], conf.level=0.95)
corrplot(M, p.mat = p.mat$p, sig.level=0.05, insig="p-value")
```
 
## Build models
 
```{r}
# use AIC to select features and find out that model with Median.Income, Home.Price and no.high.school has the lowest AIC value is 180.92

null=lm(Death.Rate~1, data=opioid)
summary(null)
full = lm(Death.Rate~.-County, data=opioid)
summary(full)
step(null, scope=list(lower=null, upper=full),direction="forward")

```
 
```{r}
# build the model with Median.Income, Home.Price and no.high.school and find out the no.high.school is not significant and the other features are significant
rline0<-lm(formula=opioid$Death.Rate ~ opioid$Median.Income+opioid$Home.Price+opioid$no.high.school)
summary(rline0)

```
 
```{r}
# build model with Median.Income and Home.Price only and find the features are still significant and the overall F  test is significant too

rline2<-lm(formula = opioid$Death.Rate ~ opioid$Median.Income+opioid$Home.Price)
summary(rline2)
```
## Check assumptions
 
```{r}
#diagnostics on residuals

plot(rline2,which=1:4)
e=residuals(rline2)

plot(opioid$Median.Income, e, xlab = "median income", ylab =
             "resid")
abline(0,0, col="red")
plot(opioid$Home.Price, e, xlab = "home price", ylab =
             "resid")
abline(0,0, col="red")


# normality and constant variance models
shapiro.test(rline2$residuals)

ncvTest(rline2)

# normality condition passed but the constant variance test failed and there are some outliers
```
## Transformation
 
```{r}
# Attempts at transformations to get constance of variance box cox, Have to artificially inflate rate=0 to be able to do boxcox. 
opioid_boxcox<-opioid
opioid_boxcox[,2][opioid_boxcox[,2] == 0] <- 0.0001
opioid_boxcox

rline_boxcox<-lm(formula = opioid_boxcox$Death.Rate~opioid_boxcox$Median.Income+opioid_boxcox$Home.Price)
boxcox(rline_boxcox)

# the best suggested transfromation is about 0.5 for y.
```
 
```{r}
# build transform model and check assumptions

rline_transform<-lm(formula = sqrt(opioid$Death.Rate) ~ opioid$Median.Income+opioid$Home.Price)

summary(rline_transform)

plot(rline_transform, which=1:4)

shapiro.test(rline_transform$residuals)
ncvTest(rline_transform)


e2=residuals(rline_transform)
plot(opioid$Median.Income, e2, xlab = "median income", ylab =
             "resid")
abline(0,0, col="red")
plot(opioid$Home.Price, e2, xlab = "home price", ylab =
             "resid")
abline(0,0, col="red")

# normality and constant variance both pass

# for Breusch-Pagan-Godfrey test, The null hypothesis for this test is that the error variances are all equal, we prefer big p-value to not reject H0

```
## Check outliers

```{r}
# for original model with median income and house price
influencePlot(rline2)
outlierTest(rline2)
influenceIndexPlot(rline2)
plot(rline2,which=3:4)

# for transform model with sqrt(y)

influencePlot(rline_transform)
outlierTest(rline_transform)
influenceIndexPlot(rline_transform)
plot(rline_transform,which=3:4)

# 22 and 25 are significant outliers for transform model
```

```{r}
# build transformation model without outliers and check assumptions


opioid_outliers<-opioid[-c(22,25),]

rline_outliers_transform<-lm(formula = sqrt(Death.Rate) ~ Median.Income+Home.Price, data=opioid_outliers)

plot(rline_outliers_transform,which = 1:4)
mmp(rline_outliers_transform,opioid_outliers$Home.Price)
mmp(rline_outliers_transform,opioid_outliers$Median.Income)

shapiro.test(rline_outliers_transform$residuals)
ncvTest(rline_outliers_transform)
e3=residuals(rline_outliers_transform)
plot(opioid_outliers$Median.Income, e3, xlab = "median income", ylab =
             "resid")
abline(0,0, col="red")
plot(opioid_outliers$Home.Price, e3, xlab = "home price", ylab =
             "resid")
abline(0,0, col="red")

# we could see that both normality and costant variance conditions pass.
```
## Summary the final model
 
```{r}
summary(rline_outliers_transform)
# R^2 is 20% and p-value is 0.002694 which is small enough
```

```{r}
# Design and implement linear regression modeling to perform statistical analysis for opioid epidemic and observed the correlation between our research and two articles suggested conclusion.
# Collect and extract data from government websites, process raw data for regression, handle missing values and build relative regression models
# Perform the statistical analyses including linear regression analysis, statistical modeling(GLM, Logistic Model, and Cox Model) with RStudio, presented the process of the whole project and create report based on finding.

```

## Future suggestions

```{r}
# use VIF to check multicollinearity
# collect more data to emprove the R^2 such as use city replace county
# could use million unit to interprate the correlation since the correlation is very small
```


```{r}
vif(rline_outliers_transform)
# we see that the VIF is both smaller than 10, then the multicollinearity is not very serious.
```

 